### ISSUE TITLE
How does one point resque towards an external redis server?

### ISSUE THREAD

**Issue by mklatsky** [Restream/redmine_resque#4]
When I run 'bundle exec rake resque:work RAILS_ENV=production QUEUE=*', the resulting error is:

**Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)**

However, redis is running on another internal server, so I need to point rescue to that server (i.e. 192.168.10.5). Thank you.

**Comment by simongartz** [comment]
I added following line to file REDMINE_DIR/plugins/redmine_resque/init.rb

```
Resque.redis = Redis.new(host:"172.17.0.12", port:6379)
```
